In [1]:
#1. Write a Python Program to Add Two Matrices?
import numpy
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,12,13],[14,15,16]])
c=a+b
c

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[12, 14, 16],
       [18, 20, 22]])

In [2]:
#2. Write a Python Program to Multiply Two Matrices?
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,12,13],[14,15,16]])
c=a*b
c

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[11, 24, 39],
       [56, 75, 96]])

In [3]:
#3. Write a Python Program to Transpose a Matrix?
a=np.array([[1,2,3],[4,5,6]])
def transpose(a):
    print(a.transpose())

<IPython.core.display.Javascript object>

In [4]:
transpose(a)


[[1 4]
 [2 5]
 [3 6]]


In [5]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
sentense=input('enter a sentense------>')
words=sentense.split()
a=sorted(words)
a

enter a sentense------>In each iteration, we check if the character is a punctuation mark or not using the membership test. We have an empty string to which we add (concatenate) the character if it is not punctuation. Finally, we display the cleaned up string.


['(concatenate)',
 'Finally,',
 'In',
 'We',
 'a',
 'add',
 'an',
 'character',
 'character',
 'check',
 'cleaned',
 'display',
 'each',
 'empty',
 'have',
 'if',
 'if',
 'is',
 'is',
 'it',
 'iteration,',
 'mark',
 'membership',
 'not',
 'not',
 'or',
 'punctuation',
 'punctuation.',
 'string',
 'string.',
 'test.',
 'the',
 'the',
 'the',
 'the',
 'to',
 'up',
 'using',
 'we',
 'we',
 'we',
 'which']

In [6]:
#5. Write a Python Program to Remove Punctuation From a String?
import string
sentense=input('enter a sentense--->')
no_punctation=''
for i in sentense:
    if i not in string.punctuation:
        no_punctation=no_punctation+i
no_punctation

enter a sentenseHey!!! My name is 'raghav'.


'Hey My name is raghav'